---
sidebar: sidebar
permalink: fsx/configuration-analysis-fsx.html
keywords: configuration issues, issues, improve, analyze, storage configuration, recommendation, recommendations
summary: "The well-architected dashboard analyzes FSx for ONTAP file system configurations regularly to determine if any there are any configuration issues."  
---
= Configuration analysis for Amazon FSx for NetApp ONTAP
:icons: font
:imagesdir: ../media/

[.lead]
The well-architected dashboard in NetApp Console analyzes storage system configurations regularly to determine if any there are any configuration issues with your Amazon FSx for NetApp ONTAP file systems. When issues are found, the dashboard shows you what the issues are and explains what needs to change to ensure your storage systems achieve peak performance, cost efficiency, and compliance with best practices. 

Key capabilities include: 

* Daily configuration analysis
* Automatic best practice validations for NetApp ONTAP storage systems and partner storage providers
* Proactive observability
* Insights to action

include::_include/well-architected-workloads.adoc[]

== Analysis requirements
For a complete file system analysis, you must do the following: 

* link:https://docs.netapp.com/us-en/console-setup-admin/concept-agent-install-options.html#agent-console-deploy[Deploy a NetApp Console agent^] or link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html[associate a link^] to set up connectivity between the file system and NetApp Console.

* Grant _view, planning, and analysis_ permissions in your AWS account. 
+
link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html[Learn how to grant permissions to an AWS account^]

include::_include/fsx-configurations.adoc[]


.What's next

link:improve-configurations-fsx.html[Implement well-architected FSx for ONTAP file system configurations]