---
sidebar: sidebar
permalink: cvo/configuration-analysis-cvo.html
keywords: Cloud Volumes ONTAP, configuration issues, issues, improve, analyze, storage configuration, recommendation, recommendations
summary: "The well-architected dashboard in NetApp Console analyzes Cloud Volumes ONTAP system configurations daily to determine if there are any configuration issues."  
---
= Configuration analysis for Cloud Volumes ONTAP
:icons: font
:imagesdir: ../media/

[.lead]
The well-architected dashboard in NetApp Console analyzes storage system configurations regularly to determine if there are any configuration issues with your Cloud Volumes ONTAP systems. When issues are found, the dashboard shows you what the issues are and explains what needs to change to ensure your storage systems achieve peak performance, cost efficiency, and compliance with best practices. 

Key capabilities include: 

* Daily configuration analysis
* Automatic best practice validations for NetApp ONTAP storage systems and partner storage providers
* Proactive observability
* Insights to action

include::../_include/well-architected-workloads.adoc[]

== Analysis requirements
For a complete Cloud Volumes ONTAP system analysis, you must link:https://docs.netapp.com/us-en/console-setup-admin/concept-agent-install-options.html#agent-console-deploy[deploy a NetApp Console agent^] to set up connectivity between your systems and the NetApp Console.

== Best practices and recommendations for Cloud Volumes ONTAP systems

The well-architected dashboard assesses storage configurations to provide an in-depth view of ONTAP configuration best practices and for compliance with the Azure Well-Architected Framework. The assessment also recommends improvements and fixes.  

The well-architected analysis categorizes configurations in the following pillars of the framework: _reliability_, _security_, _operational excellence_, _cost optimization_, and _performance efficiency_.

=== Reliability 
Reliability ensures that workloads perform their intended functions correctly and consistently, even during disruptions. 

* *Snapshot policy*
+
Schedule local snapshots for efficient backup and quick restores. Snapshots are instant, point-in-time images of your volumes. 

* *SSD capacity headroom*
+
The SSD storage tier capacity should not exceed 80% utilization. This might impact data reads and writes to your capacity pool storage tier and impact the throughput capacity of your system. When capacity runs out, data volumes become read-only. Services trying to write new data also fail.

=== Security 
Security emphasizes protecting data, systems, and assets through risk assessments and mitigation strategies. 

* *Autonomous Ransomware Protection with AI (ARP/AI)* 
+
NetApp Autonomous Ransomware Protection with AI (ARP/AI) helps enhance cyber resiliency and protect your volumes from ransomware threats. We recommend enabling ARP/AI for all volumes.

=== Operational excellence
Operational excellence focuses on delivering the best architecture and business value. 

* *Volume capacity headroom*
+
We recommend that volume capacity doesn't exceed 80% utilization. This might impact data reads and writes to your application. Volume capacity increases can be manual or automatic using the volume autogrow feature. 

* *FlexCache write mode*
+
For optimal performance, we recommend the FlexCache write mode that best suits your workload. Write-around mode provides better performance for read-heavy workloads with small files, while write-back mode provides better performance for write-heavy workloads with large files.

* *FlexCache replica size*
+
We recommend enabling volume autosize and scrubbing on cache volumes to maintain optimal size and focus the cache on frequently accessed (hot) data for peak efficiency.

* *ONTAP version compliance*
+
Upgrade to the latest ONTAP version for full compatibility, support, and access to new features. 

=== Cost optimization
Cost optimization helps you get the most value for your business while keeping costs low.

* *Overprovisioned SSD capacity*
+
An overprovisioned SSD capacity tier adds unnecessary costs. We recommend reducing the SSD tier capacity while maintaining a 20% free space buffer. A decrease operation takes several hours to several days, and other file system operations are unsupported during this time.

* *Cold data tiering*
+
Enable cold data tiering to move cold data from the SSD storage tier to lower-cost storage. We recommend applying a tiering policy to every volume. Azure Blob Storage serves as the capacity tier for inactive data.

.What's next

link:https://docs.netapp.com/us-en/console-well-architected/cvo/improve-configurations-cvo.html[Implement well-architected Cloud Volumes ONTAP system configurations]