---
sidebar: sidebar
permalink: cvo/configuration-analysis-cvo.html
keywords: Cloud Volumes ONTAP, configuration issues, issues, improve, analyze, storage configuration, recommendation, recommendations
summary: "NetApp Console analyzes storage system configurations regularly to determine if any there are any configuration issues."  
---
= Configuration analysis for Cloud Volumes ONTAP
:icons: font
:imagesdir: ../media/

[.lead]
NetApp Console analyzes storage system configurations regularly to determine if any there are any configuration issues. When issues are found, the Console shows you what the issues are and explains what needs to change to ensure your storage systems achieve peak performance, cost efficiency, and compliance with best practices. 

Key capabilities include: 

* Daily configuration analysis
* Automatic best practice validations for NetApp ONTAP storage systems and partner storage providers
* Proactive observability
* Insights to action

== Analysis requirements
For a complete Cloud Volumes ONTAP system analysis, you must do the following: 

* link:https://docs.netapp.com/us-en/console-setup-admin/concept-agent-install-options.html#agent-console-deploy[Deploy a NetApp Console agent^]. Console agent connectivity lets the Console analyze all Cloud Volumes ONTAP system configurations like data protection and performance.

* Grant _view, planning, and analysis_ permissions in your AWS account. 
+
link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html[Learn how to grant permissions to an AWS account^]

== Best practices and recommendations for Cloud Volumes ONTAP systems

NetApp assesses storage configurations to provide an in-depth view of ONTAP configuration best practices and for compliance with the AWS Well-Architected Framework. The assessment also recommends improvements and fixes.  

The well-architected analysis categorizes configurations in the following pillars of the framework: _reliability_, _security_, _operational excellence_, _cost optimization_, and _performance efficiency_.

=== Reliability 
Reliability ensures that workloads perform their intended functions correctly and consistently, even when there are disruptions. 

* *Schedule local snapshots*
+
Schedule local snapshots for efficient backup and quick restores. Snapshots are instant, point-in-time images of your volumes. 

* *SSD capacity threshold*
+
The SSD storage tier capacity should not exceed 80% utilization on an ongoing basis. This might impact data reads and writes to your capacity pool storage tier and impact the throughput capacity of your file system. Running out of capacity might result in data volumes becoming read-only, and services trying to write new data might fail. 

=== Security 
Security emphasizes protecting data, systems, and assets through risk assessments and mitigation strategies. 

* *Autonomous Ransomware Protection with AI (ARP/AI)* 
+
NetApp Autonomous Ransomware Protection with AI (ARP/AI) helps enhance cyber resiliency and protect your volumes from ransomware threats. We recommend enabling ARP/AI for all volumes.

=== Operational excellence
Operational excellence focuses on delivering the most optimal architecture and business value. 

* *Volume capacity utilization threshold*
+
NetApp recommends that volume capacity doesn't exceed 80% utilization on an ongoing basis. This might impact data reads and writes to your application. Volume capacity increases can be manual or automatic using the volume autogrow feature. 

* *Cache relationship write mode*
+
For optimal performance, NetApp recommends the cache relationship write mode that best suits your workload. Write-around mode provides better performance for read-heavy workloads with small files, whereas write-back mode provides better performance for write-heavy workloads with large files.

* *ONTAP cache volume size*
+
NetApp recommends enabling volume autosize and scrubbing on cache volumes to maintain optimal size and focus the cache on frequently accessed (hot) data for peak efficiency.

* *ONTAP version compliance*
+
Upgrade to the latest ONTAP version for full compatibility, support, and access to new features. 

=== Cost optimization
Cost optimization helps you get the most value for your business while keeping costs low.

* *Identify underutilized SSD capacity*
+
An underutilized SSD capacity tier might be incurring unnecessary costs. NetApp recommends reducing the SSD tier capacity while maintaining a 20% free space buffer above current used capacity. A decrease operation can take several hours to several days, and other file system operations are not supported during this time.

* *Data tiering policy*
+
We recommend turning on cold data tiering to move inactive data from from the SSD storage tier to lower-cost storage and reduce costs. Azure Blob Storage is used as the capacity tier for inactive data.

.What's next

link:cvo/improve-configurations-cvo.html[Implement well-architected Cloud Volumes ONTAP system configurations]